/**
 * @author Adam Long
 * @copyright 2024 - All rights reserved.
 */

//Imports
import {BlogProps} from "@/lib/props";

export const blogElements: BlogProps[] = [
    {
        id: 1,
        title: "College Goals",
        desc: "Coming into college I have three big items I want to check off my list. ",
        date: "May 5th, 2023",
        imgRef: "https://i.imgur.com/Ba2llOT.jpg",
        content: "What are your STEM-related career goals, and why have you chosen this major?\n" +
            "I have three main STEM related career goals, specifically in the lens of computer science (my major). I created these goals around Locke’s Goal Setting Theory, which is designed to make your goals challenging, realistic, and achievable. By creating my goals around Locke’s Theory, I am able to challenge myself while also being able to complete my goals during my education at Texas State University.\n" +
            "Goal One: Participate in research. I did a research project in high school discussing the Economics of Electric Vehicles, and it excited me as I got to dive deep into a field that I had a huge interest in. Unfortunately, I didn’t have a reasonable sample size and so my findings were on the lacking side, but it showed me what is possible. This semester I haven’t participated in research due to time constraints; however, I plan on setting time aside in the upcoming semesters to get involved with the program. Specifically, I want to focus on artificial intelligence, a field growing at an exponential rate. Not only do I think AI is cool, but I plan on going into it as a career.\n" +
            "Goal Two: Create an AI software. As I mentioned above, I want to try to push forward my knowledge in AI. I figured the best way to do this would be to program my own AI. I’m not exactly sure what it would do yet, but I know I want it to involve picture recognition of some form. Paired with my planned research in the field and my growing knowledge in computer science, I think it will be a challenging, fun project to work on.\n" +
            "Goal Three: Present a lecture. Public speaking is something I have always been fond of; sharing my experiences and knowledge to other people is something I’ve always enjoyed. Whether it is about my waterskiing experience, travels around America, or various mathematical subjects, I love to talk about the lessons I have learned and the things I have seen. Expressing to people what is possible and what exists is extremely fun to me. I only have gotten one opportunity to present an idea in a communications class, and I want to do more of it. I hope that by being a part of H-LSAMP will give me the connections and feedback I need to turn this goal into a reality.\n",
    },
    {
        id: 2,
        title: "The Gift that Keeps on Giving",
        desc: "Volunteering is something that I have always liked doing. Donating my time in college is no different.",
        date: "February 14, 2023",
        imgRef: "https://i.imgur.com/njtGAB5.jpg",
        content: "Getting things whether it be money or gifts makes me happy but giving said money or gifts makes me happier. That is what excites me about community service. It is the act of giving instead of getting that satisfies me. You can place materialistic items, but you’ll live with the memories of emotional thankfulness for the rest of your life. Anyone can do service, small things like mowing your grandma’s lawn up to donating millions to cancer research. Out of all these however, my favorites are integrated service. Integrated service is what I like to call serving in a field you enjoy and are most strong in. For me that is technical theatre, computer science, and mathematics.\n" +
            "Technical theatre is something I’ve been doing for more than seven years now; having my hands onto at least 20 different performances in the arts. Most of these aren’t paid, they are school productions or dance shows from within the community. I specialize in lighting design and implementation, which is picking how the lights look and programming it into the board. It is complicated specially if you don’t have a technology background, so donate my time to help where I’m strong. It’s a field that little people have knowledge in, so I build the lighting for kiddy camps, schools, and small concerts from the ground up. Giving the opportunity have hundreds of people in dance, theatre, band, and more by lighting up their stage allowing them to put on the best show possible can’t be replaced. Furthermore, I always try and teach my work to anyone interested. I’ve had parents and staff members approach me asking for lessons on how to design and program lighting for their own use. Today I have over 300 hours of service in this field from lighting up people’s day (literally) and giving lessons to those who want a deeper dive. For the advanced aspects of lighting there is a learning curve due to the programming, which I got over through computer science. \n" +
            "Computer science is what I plan on majoring in and doing as a career and I put in my best effort to help others achieve this as well. The possibilities are endless in computer science because you can work in any field you want. Programming lighting and iOS apps are my favorites but no matter what career or hobby there is some form of programmable aspect in it. Therefore, I try and pass this knowledge down to my peers. I mainly do this through my school’s UIL computer science team. Together I show them various algorithms, structures, and assets needed to succeed. I’ve taught the team for two years until I graduated high school and while I compete at the state level with a team, I make it a priority to build the skills of the future and show them the power of computation. After about 100 hours total not only did my team and I take home 3rd and 2nd place for the UIL 5A Computer Science Academic Competition in 2021 and 2022 respectively. I also trained a team so that the future talent from within my community could continue winning at the state level for years to come. Not only so they can receive trophies, but also receive scholarships to go learn computer science at universities all over the nation. Computer science requires lots of math and I try my best to guide people through that as well.\n" +
            "Mathematics always came naturally to me. I was succeeded and got A’s in my classes without trying, but with this lack of study time I decided to show others how to do the same. When compared to the other two acts of service I do/have done, math tutoring is more impromptu. I don’t have a schedule or a specific free course I offer, but I often join the group chats of classes I’ve already passed to help them out. Furthermore, when I see friends or acquaintances stressing about a math test, I’ll study with them and act like a private tutor. Not only is it better for their learning, but it helps me master teaching and helping the next person. I’m unsure exactly how many hours I’ve committed to this because it is more on the unpredictable side, but I have been doing this for four years now beginning in high school. \n" +
            "I love helping people. It’s the gift that never stops giving and is by far my favorite form of community service. Offering my assistance to others who aren’t as strong in these fields gives me the opportunity to teach them. Furthermore, not only am I helping my community, but I am also integrating my own career into my community service to enjoy the moment. \n",
    },
    {
        id: 3,
        title: "Unique Opportunities",
        desc: "Everyone is offering unique opportunities that build their character. These are some of mine.",
        date: "February 9, 2024",
        imgRef: "https://i.imgur.com/xH0HMlL.jpg",
        content: "Unique experiences are difficult to come across in an educational environment. Everyone is on an equal playing field whether they choose to specialize in the arts of theatre, band, athletics, business, or technology. Not one student truly has extra freedoms or benefits than their fellow students do. For me, unique experiences come from exceptional work in your field, and I was gratefully offered one golden opportunity that is unique to me. My private tutoring job gives me unique experiences teaching students that are currently in a place that I once filled. Tutoring allows me to learn how to teach, build a passion for helping others, and use these skills to affect my current learning at Texas State University.\n" +
            "My private tutoring experience allows me to teach others. I once thought this was easy, just restating what knowledge you currently hold; however, I could not be further from the truth. The reality is that most concepts I end up teaching to my students are trivial to me, but not them. Teaching is the art of breaking down a subject into communicable ideas that allows the learner to paint their own picture of the subject at hand. The process of taking trivial concepts and breaking them down into small, communicable steps is something that has directly impacted my everyday life. Besides tutoring, it has allowed me to be more concise in my conversations. I used to be the guy that would give you a paragraph for a one sentence answer. By breaking down what I want to say into pieces and speaking of only the most important pieces, I became more fluent in my conversations with others. Combined with a nice smile, breaking down concepts has proven to advance my conversational skills significantly.\n" +
            "I could have picked any job to have during college, why tutoring? Well tutoring allows me to interact with others. From a young age I developed my socials skills much slower than others resulting in a lack of conversation until I reached high school. Tutoring gave me an out to show others the way in whatever subject they needed. It was through tutoring others, however, that I learned of my passion to help others. Most of my clients are usually junior high or high school students who are not quite getting the subject at hand due to their teacher’s style of teaching. Sometimes all it takes is a different style of explaining a topic and it will suddenly make sense to you. For my client’s, it makes a world’s difference. Seeing their faces light up like a Christmas tree when they finally understand a concept is purely amazing. Since then, I always try to help others. It can be tutoring, sport coaching, or a flat tire I will always try to help out. It has become a hobby for me.\n" +
            "My unique tutoring experience shaped me into a different person by making me a more selfless person who strives to help others. With my newfound abilities, I sometimes even give mini lectures in my classes. I will speak about a specific subject for a few minutes about my approach to a problem given or show a different perspective about the material. My professors tend to eat up when another student is able to lecture the class. It makes it feel more inviting and relatable to everyone, let alone way more interactive.\n" +
            "I hope to gain more experience from Texas State University. I am ready for my next challenge that will allow me to help more people while also developing my character even more. I hope to present a TED Talk here as my biggest experience. It will put me in front of hundreds of people talking about something my audience can away. That talk will build my own legacy at Texas State. I have no interest in being the next Lyndon B. Johnson, I hope to be the first me.\n",
    },
    {
        id: 4,
        title: "Ten Years of Me",
        desc: "In a lyrical reflection I look back my life through the lens of music tracks.",
        date: "September 20, 2022",
        imgRef: 'https://i.imgur.com/iOeCZHf.jpg',
        content: "Year 9: CaptainSparklez & TryHardNinja - Revenge\n" +
            "I can barely remember myself at nine years old, but I can remember one key thing from this time of my life. I found a passion for computers, and what their capabilities were. This song by CaptainSparklez, a media influencer, is based on the legendary game known as Minecraft; A game I have played and still play for over ten years now. Some people say it’s crazy that a block game is an active part of my personality; however, it’s an open world game to explore, which sparked my creativity ten years ago. In this game you can build your own house or complex autonomous machines; therefore, forming skills I never would have gotten from a young age. To this day I can load Minecraft and see my nostalgic creations from ten years ago.\n" +
            "Year 10: Mario Kart Wii - Title Theme\n" +
            "With my passion for computers and using them for entertainment, I developed an interest in videogames. The Wii from Nintendo gave me lots of fun memories to relish on. The Title Theme from Mario Kart Wii is a classic for me. I would spend hours each day trying to get better and better at the game. I could feel myself getting way too competitive for my own good, so much in fact, it turned me into an extremely competitive person without knowing it. I would always want to be the fastest kid in school, the most daring, and most athletic all because of a simple go-kart racing game. \n" +
            "Year 11: Rascal Flatts - Life is a Highway\n" +
            "At age eleven, my family and I began travelling America to find all its great gems whether known or unknown. We were on a mission to find everything about American culture we could. From the birthplace of Hellen Keller, famous disabilities rights activist, to Niagara Falls, the largest waterfall known to humankind. We set out on a multi-year journey. Initially, I severely disliked not being able to play videogames; however, I learned later on to appreciate every new exploration I was travelling to see. Most people take vacations for a week to the beach or go on a cruise then come home. My family was different, we would venture out for ninety days by van to explore every detail about American culture.\n" +
            "Year 12: Whitney Houston & Wahlstedt - I Wanna Dance with Somebody [Remix]\n" +
            "There was a time where all I wanted to do was dance. Not for any reason, but just as a way of expressing myself and relaxing. At the time, all the videos of me “dancing” were considered extremely cringe, but now I just look at them and laugh. Age twelve was the year I moved to Texas and didn’t really have many friends, so another way I think about it was my way of escaping the world around me to be myself and not who others wanted me to be. To this day, I still love to dance; mainly behind closed doors of course.\n" +
            "Year 13: John Travolta & Jeff Conaway - Greased Lightnin’\n" +
            "When I turned thirteen years old and was forced to take a theatre class in junior high school. I learned that theatre is not just acting, but there is also a technical side to it too. I immediately jumped onto this opportunity and joined my first musical production team for “Grease the Musical”. In my opinion, Greased Lightnin’ is by far one of the best musical tracks I’ve ever worked with and has created lots of memories. I rarely sing but this song gave me an opportunity to let lose, and that is one of my best memories in my whole seven years of theatre. \n" +
            "Year 14: Justin Timberlake - Mirrors\n" +
            "Age fourteen was when I looked myself in the mirror and decided to make a change. Up to this point I was doing whatever I felt because it was fun in the moment. My new goal was to make more conscious decisions to put myself on a path to success and put myself ahead of the competition. Mirrors became my go to song for a long time as it made a good song to grind out the hours to. Whether it be working on new projects to enhance my understanding or schoolwork to get the grades I expected from my teenage self. There are too many memories with this song, the biggest of them however was the woodshop I spent countless hours in. I had many projects including building a CO2 drag car, notebook, and custom pen. All these I still have today and bring me back to the start of my interest in manufacturing my creative side.\n" +
            "Year 15: Macklemore & Ryan Lewis - Can't Hold Us [Exit Edit]\n" +
            "I don’t connect with the lyrics in this song. Can’t Hold Us for me is more about the feeling the song gives. Can’t Hold Us represents myself in the normal way I go about life and then suddenly, the mood switches to a more bass-like vibe that represents the side of me people rarely see. For example, when I did technical theatre, people usually saw me as a lighting crew member and nothing more. What they didn't see was the talent restricted by the choice of the musical. In my final high school days I let loose and created a lightshow for my high school’s dance team with multiple moving fixtures and parts. If you saw the show knowing what my work looked like, you never would have known it was me. The moment of surprise of people when they saw what I was able to do was something very memorable to me.\n" +
            "Year 16: Avicii - The Nights\n" +
            "Avicii, renowned DJ and remixer of music once said: “When I was 16 my father said you could do anything you want with your life. You just have to be willing to work hard to get it. That’s when I decided when I die, I want to be remembered for the life I lived, not the money I made” (Bergling, 2014). Avicii created what is now by far one of my favorite songs for life. Avicii lyricized as well as composed The Nights describing his experiences through life and what he wanted to become. The song describes how you should take every single day you live for granted and turn everyday into something productive, cool, or meaningful to yourself. There is not a specific memory associated with this song, but rather my philosophical ideals at age sixteen. Instead of sitting around watching TV or browsing the internet, I wanted to go out and explore what exists and what is possible. I spent my time dedicated to innovating, creating, and incorporating my dreams into my successes.\n" +
            "Year 17: Kesha - This is Me\n" +
            "You might have broken parts, flaws, or have made big mistakes, but these are elements that form your character and shouldn't be hidden. This is Me presents the idea that you are showing off yourself without any filter and are \"not scared to be seen\" (Kesha, 2018). This is very much like me in the way that I am not afraid to showcase who I am. I will present what I think, like, believe, or know at face value. I will show my mistakes and how I grew/am growing in whatever it may be such as technical theatre or motorsports. There were times I have thrived and been able to pass my technical skills to other people; however, there were also times I have crashed thousands of dollars worth of racing equipment. I believe it is important to show all aspects of myself to people because if I paint a perfect picture, they will expect a perfect picture.\n" +
            " Year 18: Lil Nas X - Industry Baby\n" +
            "Now that I’m a student and collegiate athlete at Texas State University I am here to show everyone what I’m capable of. There aren’t memories here, but rather opportunities for memories to be made. Whether it be engineering for Bobcat Racing, waterskiing for the Texas State, or just me and a group of men playing games on Saturday night.  I am here to make memories through pushing myself to the limit of what I’m able to do. Lil Nas perfectly represents this by dissing all his enemies and directly describing accomplishments he achieved because of his tireless dedication for them. These are the memories I want to leave Texas State University with. \n"
    },
    {
        id: 5,
        title: "Why EVs aren't the Transportation Solution of the Future.",
        desc: "After my research done in high school, I decided to rewrite this reflection piece.",
        date: "November 10, 2022",
        imgRef: "https://i.imgur.com/sYNB5jL.jpg",
        content: "Why Electric Vehicles aren’t the Transportation Solution of the Future.\n" +
            "Do you own an electric or hybrid vehicle? Chances are you don’t. Electric vehicles (EVs) are one of the newest forms of technology aimed at decreasing pollution around the globe and creating a foundation to create a society built around renewable energy. The transportation sector is responsible for roughly 14% of greenhouse gas emissions across Earth and this is projected to increase to 50% by 2030 (IEA 12). Granted this assumes that the current flow of internal combustion engines remains constant. Although electric vehicles sound like the perfect solution to the issue of pollution, there aren’t any on the roads today because of the lack of infrastructure and their effects on the environment.\n" +
            "Ever since the electric vehicle was invented in 1889 and engineered to make it a reasonable purchase (Office of Clean Energy Demonstrations). EVs have constantly been more expensive than their internal combustion engine counterparts; this includes hybrid-electric vehicles due to their complex components (Rahmani & Loureiro 10). Furthermore, electric vehicle energy must come from somewhere; implying, the electricity is coming from pollutive sources such as nuclear and coal power plants.  Lastly, the road infrastructure isn’t developed enough to support electric vehicles.\n" +
            "These novel pieces of technology are not far away from being implemented completely into society. By making modest changes in the way electric vehicles are implemented into the world can have drastic changes on their implications onto the world. I believe electric vehicles aren’t currently the transportation solution of the future without further technological advancement. The reason being is encouraging people to drive EVs instead of the convention gas powered vehicle is difficult. Rui Miao et.al., professor of industrial engineering & logistics management at Shanghai University states that the best way of breaking [EV] information down is establishing the perspectives of infrastructure, pricing, and environmental effects (4824-4825). Due to the lack of infrastructure and environmental effects electric vehicles currently should not be the primary transportation solution of the future.\n" +
            "The initial critical point to mention is the infrastructure supporting electric vehicles, which refers to the buildings and technology that are currently existing in place for EV use within a specific area (Long 4). To say there is a bareness of electric vehicle infrastructure is an understatement. Without a framework that supports electric vehicles, you cannot reliably implement them into society. For instance, if you currently drive a conventional, gas powered vehicles you have multiple options for gas stations within a ten mile radius to fill up your tank. In comparison, charging stations are few and far between. Some of these stations are so far apart you are not able to reach them without running out of battery power. Not to mention the convenience of a three minute fill up versus a three hour charge. To support, Lucas Davis from the Haas School of Business, University of California restates that “as public charging stations are becoming more common, electric vehicle charging remains nowhere near as convenient as filling up a gasoline-powered [vehicle]” (1500). The convenience for consumers is something that EVs heavily need development in. Today most people act by what is most efficient or convenient. By directly advancing infrastructure you can add more of a reason for individuals to purchase electric vehicles. \n" +
            "Not only is the direct infrastructure of electric vehicles not advanced enough, but also the framework supporting its elements. For example, to make electric vehicles fully carbon neutral one of the requirements is how you get the power to the battery. Clean energy is best generated through solar panels or wind turbines; however, these pieces of technology aren’t developed enough to supply ample amounts of power to electric vehicles. Not only is said clean energy more difficult to put into practice, but it takes longer to charge EVs then by using internal combustion engines (Ganesh and Venkatesan 362). All just to go less distance overall.\n" +
            "Lots argue that the primary reason to push for electric vehicles as the solution for transportation mention the environmental effects electric vehicles have on the world. When discussing the environmental impact, it is important to consider the entire process. While electric vehicles don’t emit carbon dioxide into Earth’s atmosphere directly you do need to know where that energy comes from. The coal power plants that convert fossil fuels into electric energy are still polluting the atmosphere. Defending EVs though is Dr. Brown, professor of mechanical engineering for Mississippi State University claiming that compared to the 32.8% efficiency of internal combustion vehicles, EVs are far more efficient with a 95% efficiency rate (Brown & Liu 50-51). The efficiency of electric vehicles open the doors for them to become more viable options; however, with their current push factors and implementation it is hard to adopt these pieces of technology.\n" +
            "Furthermore, the mining of lithium for batteries creates a different type of pollution. As described by Yumiko Iwafune, professor at the Institute of Industrial Science, University of Tokyo, states “lithium manganese oxide–lithium nickel cobalt manganese oxide (LMO–NMC) Sanyo technology” is used in the creation of batteries (Iwafune & Ogimoto 3). When mining for lithium, intensive chemicals and overage amounts of water are used to extract the lithium into a usable state to be implemented into electric vehicles. While lithium mining may not be polluting the atmosphere, it is polluting the earth’s soil and water resources which you can argue has more relevance due to their scarcity.\n" +
            "An important note to make is that electric vehicles are, relatively speaking, a new technology being implemented into society at a rapid pace. With technology growing every second of every day it is reasonable to predict that newer innovations will arise to solve all forms of pollution altogether. With this mindset and outlook onto the future, EVs will become a dominant form of transport throughout the world. For now, we can only assume infrastructure and environmental awareness will progress at a constant rate to ensure stability. \n" +
            "To elaborate, electric vehicles are in concept one of the best possible solutions to solve pollution while advancing our technological curiosities on the side. Although EVs have lots of positives making them more viable options, they also have lots of negatives to counter including lacking infrastructure and environmental effects. It is important for today’s society to understand why electric vehicles are not an optimal transportation solution for the future to make more informed choice when purchasing an EV. I support electric vehicles and believe they are an example of what humanity and modern science is capable of; however, until further technological advances arise, I believe EVs present more harm than value. Until electric vehicular technology advances, think about what type of car you buy before you buy it.\n"
    },
    {
        id: 6,
        title: "Artificial Intelligence within Classrooms",
        desc: "Is the introduction of AI into classrooms a benefit or a consequence?",
        date: "March 2nd, 2023",
        imgRef: "https://i.imgur.com/SULnxy8.jpg",
        content: "As society adapts to the future, so do our wants as a human species. These wants can make obsolete objects become necessary or allow taboo topics to become commonplace. We have seen this many times before with examples being the smart phone, tattoos, and recreational cannabis usage. All these things may have affected us in our daily lives; however, one stands out of the rest. Artificial intelligence, commonly known as AI, is a computational method in which inanimate objects can think like the human mind. Through complex algorithms such as machine learning, neural networks, and data mining, an electronic circuit can begin to outperform its human counterparts. The possibilities become endless for us to learn and achieve our goals at a rate faster than ever before, but this isn’t without its limitations. One contemporary example of such limitations is the art of masking the writers abilities; turning a paper into what appears to be a well written masterpiece when in reality it is just a person asking a robot the right questions. Currently, the most popular AI writing software is known as ChatGPT. Developed by OpenAI, ChatGPT uses publicly available data from the internet up to the year 2021 (OpenAI). While aimed to satisfy the curiosity of the public for research purposes, one demographic is using the software for other reasons. College students are notorious for finding the low hanging fruit when it comes to completing assignments and essays are no different. Through ChatGPT and other AI software, students can forge a single question or statement into a 500 word mini essay (OpenAI). AI used in this context introduces the issue of students not submitting works representing their abilities and the students don’t end up learning anything because of using the AI; conversely, many university students falsely believe that AI is a tool to assist them in their learning.\n" +
            "To start, the college students who use artificial intelligence software are not submitting their own work. Which for starters matches the definition of plagiarism. It might not be traditional plagiarism since it isn’t an owned work necessarily. As defined by Merriam-Webster, to plagiarize is to “present [a work] as new and original; an idea or product derived from an existing source” (Merriam-Webster). Most, if not all, university campuses have strict plagiarism policies prohibiting the unsolicited use of non-original works; therefore, it is safe to say that using artificial intelligence within one’s own work is also considered a violation of these policies. The reason using artificial intelligence within a work is considered plagiarism is because while it can be seen as new and original the work is derived from an existing source. The source here instead of being a website or academic journal is a robot. An argument can also be made towards ChatGPT being its own website placing it into the concurrent domain of already existing policies regarding plagiarism.\n" +
            "Secondly, the entire purpose of writing a paper is to show what you know in proper English. When you use a computer program to do that for you, what is the purpose of writing the paper in the first place? College students pay excessive amounts of money, some getting into increased (wording?) levels of debt, just to submit papers that aren’t their own work. A study done at NC State University states that out of twenty students, eight opted to use an artificial intelligence software (Fyfe 4). The appendix of this report shows all the submitted papers with highlights used to show what isn’t original work. From those who opted to fully use the software, less than ten percent of the work was deemed to be original (Fyfe 4). The goal of university from a general perspective, isn’t to receive a special sheet of paper. The end goal is to gain knowledge that will assist in a future career path. Some students recognized this fact and chose to not use artificial intelligence assistance in their paper. The most common response related to the idea that forming a paper together using contrasting, separately written ideas was more difficult than writing an original work. \n" +
            "Regardless, some students would argue that using artificial intelligence software enhances their learning opportunities by showing them how they can improve their writing. The primary argument stated is that students should be able to use all the resources available to them. The issue though is that the students overlook a key concept here, these resources that are available need to be used correctly. For example, when in mathematics the calculators aren’t used for getting the answer. The calculators are used to check the answer to ensure it is correct. Dan Milmo, editor for The Guardian, wrote an article reporting on International Baccalaureate’s acceptance of ChatGPT. They allow the students in their program to cite the source using proper style (Milmo). The idea here is to support the use of the software within papers because you can’t cite an entire paper under one source; therefore, what the student submits has to be, in some part, an original work. Furthermore, creating a dependency on ChatGPT for writing papers let’s a problem arise: A computer only does what it is told. Basically, a computer can’t critically think and relies on its instructions in the code to make decisions. If an artificial intelligence algorithm isn’t trained completely there will be inaccuracies (Gunning, et al. 2). A prime example of this is when ChatGPT chooses to cite because sometimes the software will cite a source that doesn’t exist. As one can imagine, fabricated information or miscited sources are frowned upon in academic works. The internet has, for all intents and purposes, an infinite amount of information and for an AI to find patterns in the spaghetti mess that is the World Wide Web would be near impossible due to the exponential nature of AI understanding (Chen, et al. 10-11, OpenAI). \n" +
            "For this purpose, we need to state where the line is to be drawn.  The line should be drawn at limiting the potential of the AI software. By limiting the AI versus outright banning it, the positive uses of the software are still enabled allowing to be a proper tool for anything, including educational purposes. I’ve been in the computer science field for five years and I suggest we implement new artificial intelligence software to indirectly limit the softwares that specifically give university students an academic edge. Using current artificial intelligence algorithms, a computer program can be trained to detect the use of computer generated works submitted. With this solution university students are limited in their usage of a computer program to complete their assignment. As a result, the students are still allowed to use the AI tools at their disposal to correct their mistakes and make minor improvements to their works. At the end of the day, AI within a learning environment is still a new and developing concept, given enough time proper action can be achieved.\n",
    }
];
